name: A workflow for Integration Testing
on: push

#tis almost 1 am goodnigh be back later...
jobs:
  build:
    name: Assessment action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
