name: Test Workflow

on:
  push:
    branches:
      - master
      - feature/DevelopGUI
  pull_request:
    branches:
      - master
      - feature/DevelopGUI

jobs:
  build:
    name: Run Maven Tests
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up the JDK 17 adopt
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: runs unit test and maven clean
      - name: Run Unit Tests
        run: mvn clean test

      # Step 5: upload the results of the run
      - name: Upload Test Results
        if: always() # will always run even if the tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports # the default tests or reports path
