name: Automation Testing
on:
   push:
     branches: 
       -Master
jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code 
        uses: actions/checkout@v3

        -name: set up JDK
         uses: actions/setup-java@v3
         with:
         distribution: ''
         java=version: ''

        -name: Cache Maven repository
         uses: actions/cache@v3
         with:
         path: ~/.m2/repository
         
