name: A workflow for Testing Purposes
on:
 push:
  branches:
   -Master
   -New-Feature
  
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-20.04
    #checking out to the code.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #setting up java or testing enviroment.
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          #cacheing maven dependancies.
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-key:  |
          ${{ runner.os }}-maven

         #run tests on maven.
      - name: Run Maven Tests
        env:
          HIBERNATE_CONFIG: hibernate.cfg.xml
          run: mvn clean test
           #uploading the test reports
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with: 
           name: test-results
           path: target/surefire-reports/
        
      - name: Run Integration Tests
        run: mvn clean verify -p integration-tests
             
        
         
       
   
          
         
